version: '3.8'

services:

  web:
    build: .
    restart: always
    env_file:
      - .env  
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      
# volumes:
#   mysql_data:
