# Generated by Django 6.0.3 on 2026-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='catalog.OrderItem', to='catalog.product'),
        ),
    ]
