# Generated by Django 6.0.3 on 2026-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='breaking_load',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрывная нагрузка (кгс)'),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Диаметр (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_in_pack',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кол-во в упаковке (м)'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид упаковки'),
        ),
    ]
