# Generated by Django 6.0.3 on 2026-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_quantity_product_breaking_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Количество в шт'),
        ),
    ]
