# Generated by Django 6.0.3 on 2026-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Кол-во в шт (м)'),
        ),
    ]
