# Generated by Django 6.0.3 on 2026-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='breaking_load',
        ),
        migrations.AddField(
            model_name='product',
            name='breaking_load_display',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрывная нагрузка'),
        ),
        migrations.AddField(
            model_name='product',
            name='breaking_load_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Разрывная Нагрузка (кгс)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.FloatField(blank=True, help_text='При написании чисел с плавающей запятой используйте точку (.)', null=True, verbose_name='Диаметр (мм)'),
        ),
    ]
