# Generated by Django 6.0.3 on 2026-05-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_breaking_load_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанные товары', 'verbose_name_plural': 'Заказанные товары'},
        ),
    ]
